### ISSUE TITLE
week 01 回饋

### ISSUE THREAD

**Issue by azole** [Harris0716/git-practice#1]
讓我們來練習對技術有更深一層的觀察與探索

例如你這樣寫
> blob存放在.git資料夾中的objects資料夾中。

那到底是怎麼放的？你實際觀察到什麼？實際觀察到的變化又有什麼意義？

> commit message應該要簡潔，讓人一目了然，具體說明做了哪些更改

你寫的應該是想要達成的目標，但具體要怎麼做才能做到？

試著真正理解一個技術，試試看對技術有更多的思考，試著對於自己寫下的句子、讀到的東西，能透過實驗觀察找到佐證。

**Comment by Harris0716** [comment]
老師好，我會利用這一兩天把作業1再修改一下，或是重寫，我會用一個簡單的範例實際紀錄.git的變化，完成後會在issue這裡回覆老師，謝謝！

**Comment by azole** [comment]
沒關係，接下來把專注力放在 week 02 之後的作業上，後續的作業要提醒自己多深度思考一些。

**Comment by azole** [comment]
這個 issue 可以先 close。

補充，如果你自己想要更新 week 01 作業，當然也是可以，只是我這邊不要求。

**Comment by Harris0716** [comment]
好的，謝謝老師！
